name: Run pytest

on:
  pull_request:
    branches:
      - main

jobs:
  Run-pytest:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - name: Install Poetry Action
      uses: snok/install-poetry@v1.3.3
    - name: Test with pytest
      run: |
        poetry install
        poetry run pytest
