name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Install Poetry Action
      uses: snok/install-poetry@v1.3.3
    - name: Test with pytest
      run: |
        poetry run pytest
